### ISSUE TITLE
Export data as CSV and JSON

### ISSUE THREAD

**Issue by idris** [TechForPalestine/boycott-israeli-consumer-goods-dataset#5]
[The RFC](https://github.com/orgs/TechForPalestine/discussions/20) proposes output formats of CSV and JSON.

Create scripts (in Python?) to read the YAML data and export as CSV and JSON.

Run those scripts and commit those artifacts to git.

Add pre-commit git hook that runs the scripts.  Also add a Github Action that asserts that the CSV and JSON are up-to-date with the YAML before a PR can be merged.

**Comment by mohshbool** [comment]
hello.
first of all, i just want to say that i love what you guys are doing!
i want to take upon myself to try implementing the action proposed in this issue.
i have a couple of inquiries before i start with this, would you be open to a quick chat sometime during the week? my time zone is CET.

**Comment by THM222** [comment]
> hello. first of all, i just want to say that i love what you guys are doing! i want to take upon myself to try implementing the action proposed in this issue. i have a couple of inquiries before i start with this, would you be open to a quick chat sometime during the week? my time zone is CET.

have you joined our [discord](https://techforpalestine.org/discord-invite)? discussion is ongoing in tfp-consumer-boycott-data and we can have a chat/call tomorrow or wed

**Comment by mohshbool** [comment]
> > hello. first of all, i just want to say that i love what you guys are doing! i want to take upon myself to try implementing the action proposed in this issue. i have a couple of inquiries before i start with this, would you be open to a quick chat sometime during the week? my time zone is CET.
> 
> have you joined our [discord](https://techforpalestine.org/discord-invite)? discussion is ongoing in tfp-consumer-boycott-data and we can have a chat/call tomorrow or wed

Thank you for your response.
I have not joined the Discord because I do not have an account. 
Is there any alternative ways of contact? Perhaps we can have a virtual meeting or if you could share some relevant documents.

**Comment by dev4justice** [comment]
@idris looks like the RFC link is broken
